name: Laravel Deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy using SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 24700
        script: |
          cd /home/trinhnguyen/docker/cicd
          sudo -S git fetch origin
          sudo -S git checkout main
          sudo -S git pull
          sudo -S docker exec -it laravel_cicd sh -c "composer install --no-dev && npm install && npm run build"

